# Generated by Django 5.1.3 on 2024-12-12 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='tone',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], default='Major', max_length=10),
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.JSONField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='keys.keys')),
            ],
        ),
    ]
